### ISSUE TITLE
Causes Juke Boxes to eat music discs on a server

### ISSUE THREAD

**Issue by RedOptic** [Gaming32/bingo#29] opened 2024-07-26 21:14 UTC
No idea why but when you have the mod installed on a server on fabric 1.21 and a player puts a disc in a juke box it just deletes the music disc.

**Comment by Earthcomputer** [comment] 2024-07-26 22:22
Sorry but there is just no way this is caused by clientcommands, try your other mods.

**Comment by Earthcomputer** [comment] 2024-07-26 22:22
Oops forgot this is the bingo repo

**Comment by Gaming32** [comment] 2024-07-26 22:36
Can you post logs?

**Comment by RedOptic** [comment] 2024-07-26 23:23
> Can you post logs?


Here are the logs from when I tested on single player:
https://pastebin.com/cQRcAeVX

There's no error output on client or server side logs when the issue happens. Also just tested on single player and the issue happens there too.

Only things that are loaded are:
Fabric 0.15.11
Bingo 1.1.10 for Fabric
Fabric API 0.100.7 

I'm not sure why this mod would be causing it, but it seems like Minecraft is trying to put the disc in the jukebox but the jukebox's data doesn't change causing the jukebox to still be empty and not play anything even though the disc was taken out of the players hand.

**Comment by Gaming32** [comment] 2024-07-26 23:27
Actually this was fixed in #26.

**Closed by Gaming32** 2024-07-26 23:27 UTC
